# ============================================================
# Zephyr Project Configuration
# ============================================================

# Console / printk
CONFIG_PRINTK=y

# Assertions
CONFIG_ASSERT=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Main thread stack
CONFIG_MAIN_STACK_SIZE=2048

# ------------------------------------------------------------
# Add project-specific configuration below
# ------------------------------------------------------------

# ---------------------------------------------------------
# DEOS Core Prototype
# ---------------------------------------------------------

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# CAN desteği
CONFIG_CAN=y

